version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ml-sam-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jgzo4gdw1vyb"
s3_prefix = "ml-sam-sample"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["InferenceFunction=822507008821.dkr.ecr.us-east-1.amazonaws.com/mlsamsamplee645473b/inferencefunction7c73919drepo"]
