version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "multi-step-workflow"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jgzo4gdw1vyb"
s3_prefix = "multi-step-workflow"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
